config/routes.rb
Rails.application.routes.draw do
 
  
  resources :teams
  resources :cases
  resources :positions
  devise_for :users, :controllers => { :registrations => "user/registrations" }
   root 'welcome#index'
   
   get 'myteam', to: 'mywork#myteams'
    get 'mycases', to: 'mywork#show'
 
end

app/models/case.rb
class Case < ActiveRecord::Base
  belongs_to :user
end

app/models/position.rb
class Position < ActiveRecord::Base
    has_many :users
end

app/models/team.rb
class Team < ActiveRecord::Base
    has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :cases
  
  belongs_to :team
  belongs_to :position
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@tek-experts.com+\z/
  validates :email, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_case, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:index]

  # GET /cases
  # GET /cases.json
  def index
    @cases = Case.all
  end

  # GET /cases/1
  # GET /cases/1.json
  def show
  end

  # GET /cases/new
  def new
    @case = Case.new
  end

  # GET /cases/1/edit
  def edit
  end

  # POST /cases
  # POST /cases.json
  def create
    @case = Case.new(case_params)
    @case.user = current_user
    respond_to do |format|
      if @case.save
        format.html { redirect_to @case, notice: 'Case was successfully created.' }
        format.json { render :show, status: :created, location: @case }
      else
        format.html { render :new }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cases/1
  # PATCH/PUT /cases/1.json
  def update
    respond_to do |format|
      if @case.update(case_params)
        format.html { redirect_to @case, notice: 'Case was successfully updated.' }
        format.json { render :show, status: :ok, location: @case }
      else
        format.html { render :edit }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cases/1
  # DELETE /cases/1.json
  def destroy
    @case.destroy
    respond_to do |format|
      format.html { redirect_to cases_url, notice: 'Case was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case
      @case = Case.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_params
      params.require(:case).permit(:public_id, :status_id, :action_plan)
    end
    
    def require_same_user
      if current_user != @case.user && !current_user.admin?
        flash[:danger] = "You can't do that action."
        redirect_to root_path
      end
    end
    
    def require_admin
      if current_user and !current_user.admin?
        flash[:danger] = "Only admin users can perform that action"
        redirect_to root_path
      end
    end
end

app/controllers/mywork_controller.rb
class MyworkController < ApplicationController
  

  
  def show
    @mywork = User.find(current_user.id)
  end
  
  def myteams
    @myteam = Team.find(current_user.team_id)
  end
  
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]
  before_action :require_admin
  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:name)
    end
    
    def require_admin
      if current_user and !current_user.admin?
        flash[:danger] = "Only admin users can perform that action"
        redirect_to root_path
      end
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :manager_email)
    end
    
    def require_admin
      if current_user and !current_user.admin?
        flash[:danger] = "Only admin users are able to do that"
        redirect_to root_path
      end
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  
  
  protected
  
  def  configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :team_id, :position_id] )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cases/_cases.html.erb
 <% obj.each do |c| %>
  <tr>
    <td><%= link_to c.id, case_path(c) %></td>
    <td><%= c.public_id %></td>
    <td><%= c.status_id %></td>
    <td><%= c.action_plan %></td>
    <td><%= c.user.email %></td>
    <td>
      
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_case_path(c), :class => 'btn btn-default btn-xs' %>
      <% if current_user and current_user.admin? %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    case_path(c),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-xs btn-danger' %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/cases/_form.html.erb
<%= form_for @case, :html => { :class => "form-horizontal case" } do |f| %>

  <% if @case.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @case.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :public_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :public_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:public_id) %>
  </div>
  <div class="form-group">
    <%= f.label :status_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status_id) %>
  </div>
  <div class="form-group">
    <%= f.label :action_plan, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :action_plan, :class => 'form-control' %>
    </div>
    <%=f.error_span(:action_plan) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <% if current_user and current_user.admin? %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    cases_path, :class => 'btn btn-default' %>
        <% else %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                      mycases_path, :class => 'btn btn-default' %>
        <% end %>
    </div>
  </div>

<% end %>

app/views/cases/edit.html.erb
<%- model_class = Case -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cases/index.html.erb
<%- model_class = Case -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:public_id) %></th>
      <th><%= model_class.human_attribute_name(:status_id) %></th>
      <th><%= model_class.human_attribute_name(:action_plan) %></th>
      <th>Created by</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% if current_user and current_user.admin? %>
      <%= render 'cases', obj: @cases %>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_case_path,
            :class => 'btn btn-primary' %>

app/views/cases/new.html.erb
<%- model_class = Case -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cases/show.html.erb
<%- model_class = Case -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:public_id) %>:</strong></dt>
  <dd><%= @case.public_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status_id) %>:</strong></dt>
  <dd><%= @case.status_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:action_plan) %>:</strong></dt>
  <dd><%= @case.action_plan %></dd>
</dl>
<% if current_user and current_user.admin? %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
                cases_path, :class => 'btn btn-default'  %>
<% else %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
                 mycases_path, :class => 'btn btn-default'  %>
<% end %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_case_path(@case), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                case_path(@case),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TekFromhome" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="blue-body">
    <% unless (controller_name=="registrations" && action_name=='new') || (controller_name=="sessions" && action_name=='new')%>
      <div class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%#= link_to "Tek-From-Home", root_path, class:"navbar-brand "%>
          <%= link_to root_path, class:"navbar-brand " do %>
           <%= image_tag "logo3.png"%>
          <% end %>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
              <% if current_user and current_user.admin? %>
                <ul class="nav navbar-nav">
                  <li><%= link_to "Teams", teams_path  %></li>
                  <li><%= link_to "Positions", positions_path  %></li>
                  <li><%= link_to "Cases", cases_path  %></li>
                </ul>
              <% end %>
              <ul class="nav navbar-right col-md-4">
                <% if current_user %>
                  <li class="col-md-8 user-name">
                  <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
                  </li>
                  <li class="col-md-1"> </li>
                  <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
                <% else %>
                  <li class="col-md-4 pull-right">
                  <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
                  </li>
                   <li class="col-md-4 pull-right">
                  <%= link_to('Sign up', new_user_registration_path, class: 'btn btn-primary', title: 'Sign In') %>
                  </li>
                <% end %>
              </ul>
            </div>
        </div>
      </div>
  
      <div class="container white-body">
        <div class="row">
          <div class="col-lg-10">
    <% end %>
            <%= bootstrap_flash %>
            
            <%= yield %>
          </div>
          <% if current_user %>
            <div class="col-lg-2">
              <div class="well sidebar-nav">
                <h3>Menu</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Actions</li>
                  <li><%= link_to "My cases", mycases_path  %></li>
                  <li><%= link_to "My team", myteam_path  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
          <% end %>
        </div><!--/row-->
  
        <footer>
          <p></p>
        </footer>
  
      </div> <!-- /container -->
    
  </body>
</html>

app/views/mywork/_myteam.html.erb
 <% obj.each do |c| %>
  <tr>
   <%#= link_to c.id, case_path(c) %>
    <td><%= c.email %></td>
    <% if current_user and current_user.admin? %>
        <td>
          
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_case_path(c), :class => 'btn btn-default btn-xs' %>
         
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        case_path(c),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
        </td>
    <% end %>
  </tr>
<% end %>

app/views/mywork/myteams.html.erb
<h1> <%= @myteam.name %></h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Roster</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render 'myteam', obj: @myteam.users %>
  </tbody>
</table>
<%#= link_to t('.new', :default => t("helpers.links.new")),
            new_case_path,
            :class => 'btn btn-primary' %>

app/views/mywork/show.html.erb
<h1> <%= @mywork.email %>'s Cases</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>public_id </th>
      <th>status</th>
      <th>Action plan</th>
      <th>Created by</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%= render 'cases/cases', obj: @mywork.cases %>
  </tbody>
</table>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_case_path,
            :class => 'btn btn-primary' %>

app/views/positions/_form.html.erb
<%= form_for @position, :html => { :class => "form-horizontal position" } do |f| %>

  <% if @position.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @position.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                positions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/positions/edit.html.erb
<%- model_class = Position -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/positions/index.html.erb
<%- model_class = Position -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= link_to position.id, position_path(position) %></td>
        <td><%= position.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_position_path(position), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      position_path(position),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_position_path,
            :class => 'btn btn-primary' %>

app/views/positions/new.html.erb
<%- model_class = Position -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/positions/show.html.erb
<%- model_class = Position -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @position.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              positions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_position_path(@position), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              position_path(@position),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>